import "./globals.css";
import "@repo/ui/styles.css";
import '@mantine/core/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MantineLayout from "./mantine";
import { Providers } from "./store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MantineLayout>
            {children}
          </MantineLayout>
        </Providers>
      </body>
    </html>
  );
}
